from __future__ import annotations

import random
import re
from pathlib import Path

from starter.v1.catalog import coarse_category, display_clean, field_text, flatten_phrases

from .llm_client import cached_json_call

_PRICE_BAND_BOUNDS: tuple[tuple[float, float | None], ...] = (
    (0.0, 15.0),
    (15.0, 30.0),
    (30.0, 50.0),
    (50.0, 80.0),
    (80.0, None),
)
PRICE_BAND_LABELS = ("under_15", "15_to_30", "30_to_50", "50_to_80", "80_plus")
NEGATION_RE = re.compile(
    r"\b(?:do not|don't|does not|doesn't|did not|didn't|is not|isn't|are not|aren't|"
    r"was not|wasn't|were not|weren't|cannot|can't|won't|shouldn't|no real|not real|"
    r"not genuine|not made|not intended|not suitable|not recommended|not for|free of|"
    r"free from|instead of|avoid|never)\b",
    re.IGNORECASE,
)


# Price bands are only a compact input representation; natural wording is generated by the LLM.
def price_band(price: object) -> str | None:
    if price in (None, ""):
        return None
    try:
        value = float(price)
    except (TypeError, ValueError):
        return None
    for (_, high), label in zip(_PRICE_BAND_BOUNDS, PRICE_BAND_LABELS):
        if high is None or value < high:
            return label
    return PRICE_BAND_LABELS[-1]


def price_band_bounds(label: str) -> tuple[float, float | None]:
    return _PRICE_BAND_BOUNDS[PRICE_BAND_LABELS.index(label)]


def band_reference_price(label: str, rng: random.Random) -> float:
    low, high = price_band_bounds(label)
    if high is None:
        high = low * 2.0
    return round(rng.uniform(low, high), 2)


def browsing_budget_ceiling(exact_price: float) -> float:
    ceiling = exact_price * 1.8
    step = 5.0 if ceiling < 50.0 else 10.0
    rounded = round(ceiling / step) * step
    return max(rounded, exact_price + step)


def item_category(product: dict) -> str:
    return coarse_category(product.get("categories") or [])


def item_text(product: dict) -> str:
    """Build the exact catalog text shown to the LLM extractor."""
    parts = [
        f"TITLE: {display_clean(product.get('title') or '')}",
        "FEATURES:",
        *(f"- {phrase}" for phrase in flatten_phrases(product.get("features"))),
        "DETAILS:",
        *(f"- {phrase}" for phrase in flatten_phrases(product.get("details"))),
        "DESCRIPTION:",
        *(f"- {phrase}" for phrase in flatten_phrases(product.get("description"))),
        f"CATEGORIES: {field_text(product.get('categories'))}",
        f"STORE: {field_text(product.get('store'))}",
    ]
    return "\n".join(parts)


def _comparable(text: str) -> str:
    """Normalize formatting only; punctuation and words remain evidence-sensitive."""
    return re.sub(r"\s+", "", str(text or "")).casefold()


def _evidence_span_exists(evidence: str, corpus: str) -> bool:
    """Accept reflowed quotes, but never evidence assembled from separate spans."""
    return _comparable(evidence) in _comparable(corpus)


def _significant_tokens(value: str) -> list[str]:
    return [token for token in re.findall(r"[a-z0-9]+", value.casefold()) if len(token) > 2]


def verify_claim(
    claim: object, corpus: str, *, allow_negation: bool = False
) -> tuple[str | None, str | None]:
    """Accept an LLM claim only when its evidence is quoted and non-negated."""
    if claim is None:
        return None, None
    if not isinstance(claim, dict):
        return None, "claim is not an object"
    value = claim.get("value")
    evidence = claim.get("evidence")
    if not isinstance(value, str) or not value.strip():
        return None, "missing value"
    if not isinstance(evidence, str) or not evidence.strip():
        return None, "missing evidence"
    if not _evidence_span_exists(evidence, corpus):
        return None, f"evidence not found in listing: {evidence[:70]!r}"
    if NEGATION_RE.search(evidence) and not allow_negation:
        return None, f"evidence is negated: {evidence[:70]!r}"
    if allow_negation and NEGATION_RE.search(evidence) and not NEGATION_RE.search(value):
        return None, "use_case value does not preserve evidence negation"
    tokens = _significant_tokens(value)
    if tokens and not any(token in _comparable(evidence) for token in tokens):
        return None, f"value {value!r} is not supported by its evidence"
    return display_clean(value), None


EXTRACTED_ATTRIBUTES = ("material", "color", "size", "style", "use_case", "feature", "other")


def verify_extraction(product: dict, claims: dict) -> tuple[dict[str, str], list[str]]:
    corpus = item_text(product)
    verified: dict[str, str] = {}
    rejected: list[str] = []
    for attribute in EXTRACTED_ATTRIBUTES:
        value, reason = verify_claim(
            claims.get(attribute), corpus, allow_negation=attribute == "use_case"
        )
        if value is not None:
            verified[attribute] = value
        elif reason:
            rejected.append(f"{attribute}: {reason}")

    options = claims.get("size_options")
    if isinstance(options, list):
        clean_options = [display_clean(option) for option in options if display_clean(option)]
        if clean_options:
            verified["size_options"] = ", ".join(dict.fromkeys(clean_options))
        if "size" in verified and len(clean_options) > 1:
            del verified["size"]
            rejected.append(f"size: listing stocks {len(clean_options)} sizes")
    return verified, rejected


def derived_attributes(product: dict) -> dict[str, str]:
    attributes = {"category": item_category(product)}
    store = display_clean(product.get("store") or "")
    if store:
        attributes["brand"] = store
    band = price_band(product.get("price"))
    if band:
        attributes["budget"] = band
    return attributes


def llm_extract_attributes(product: dict, writer, cache_dir: Path) -> tuple[dict[str, str], list[str]]:
    cache_path = cache_dir / f"{product['parent_asin']}.json"
    claims = cached_json_call(cache_path, lambda: writer.extract(item_text(product)))
    verified, rejected = verify_extraction(product, claims)
    return {**derived_attributes(product), **verified}, rejected
